### ISSUE TITLE
Message Attribute is not passing

### ISSUE THREAD

**Issue by onlyauvy** [wso2-extensions/esb-connector-amazonsqs#28]
**Description:**
Message Attribute is not passing

Sending like this 
```
<amazonsqs.sendMessage>
	<queueId>{$ctx:sqsId}</queueId>
	<queueName>{$ctx:sqsName}</queueName>
	<messageBody>{$ctx:traceId}</messageBody>
	<messageAttributes>MessageAttribute.1.Name=contentType&amp;MessageAttribute.1.Value.DataType=String&amp;MessageAttribute.1.Value.StringValue=application/json</messageAttributes>
</amazonsqs.sendMessage>
```

using wso2 ei 6.6.0

**Suggested Labels:**
amazonsqs.sendMessage, messageAttributes

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/product-ei/issues/5595
